# Generated by Django 4.1.7 on 2023-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoHunters', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
