# Generated by Django 4.1.7 on 2023-04-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoHunters', '0004_alter_user_score_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
