# Generated by Django 4.1.7 on 2023-04-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoHunters', '0005_alter_user_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
