# Generated by Django 4.1.7 on 2023-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoHunters', '0006_delete_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
